/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package mod_agendar;

import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Antrax
 */
public class pantalla2 extends javax.swing.JFrame {
     String fecha;
     int idcliente;
int[ ] cl = new int[1000];
    /**
     * Creates new form pantalla2
     */
    public pantalla2() throws SQLException {
        initComponents();
        this.setLocationRelativeTo(null);
        mostrardatos();
       cbbclient();
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TIPOEV = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        label1 = new java.awt.Label();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Bbuscar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jcliente = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jhora = new javax.swing.JComboBox();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        degustacion = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabeven = new javax.swing.JTable();
        Bagendar = new javax.swing.JButton();
        jminutos = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        jfecha = new javax.swing.JTextField();
        bAceptar = new javax.swing.JButton();
        renta = new javax.swing.JRadioButton();
        boca = new javax.swing.JRadioButton();
        jComboBox4 = new javax.swing.JComboBox();
        jeve = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tevent = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        label1.setText("label1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Agendar eventos y degustaciones");
        setForeground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jLabel1.setText("Eventos Próximos:");
        jLabel1.setName("Eventos Proximos:"); // NOI18N

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jLabel2.setText("CONSULTAR FECHAS");

        jLabel3.setText("Selecciona Fecha:");

        Bbuscar.setText("Buscar");
        Bbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BbuscarActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jLabel4.setText("AGENDAR FECHA");

        jcliente.setName(""); // NOI18N
        jcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jclienteActionPerformed(evt);
            }
        });

        jLabel8.setText("Nombre del Cliente:");

        jLabel11.setText("Hora:");

        jhora.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22" }));
        jhora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jhoraActionPerformed(evt);
            }
        });

        TIPOEV.add(degustacion);
        degustacion.setText("Degustación");

        tabeven.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tabeven);

        Bagendar.setText("Agendar");
        Bagendar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BagendarActionPerformed(evt);
            }
        });

        jminutos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "00", "30" }));

        jLabel13.setFont(new java.awt.Font("Script MT Bold", 0, 24)); // NOI18N
        jLabel13.setText("Agendar eventos y degustaciones");

        jfecha.setEditable(false);

        bAceptar.setText("Aceptar");
        bAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAceptarActionPerformed(evt);
            }
        });

        TIPOEV.add(renta);
        renta.setText("Renta Mobiliario");
        renta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rentaActionPerformed(evt);
            }
        });

        TIPOEV.add(boca);
        boca.setText("Bocadillos");

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));

        jeve.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Boda", "15 Años", "Bautizo", "3 años", "Cumpleaños" }));
        jeve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jeveActionPerformed(evt);
            }
        });

        jLabel5.setText("Evento:");

        jLabel6.setText("Ciudad del Evento:");

        tevent.setText(" ");

        jLabel7.setText("Fecha:");

        jButton4.setText("RealizarCotización");

        jButton5.setText("Cerrar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel9.setText("Min:");

        jLabel10.setText("Comienzo del evento");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(Bbuscar)
                        .addGap(18, 18, 18)
                        .addComponent(bAceptar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel13)
                        .addGap(91, 91, 91))
                    .addComponent(jSeparator1)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addGap(384, 384, 384))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(jLabel6))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel11))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel7)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jeve, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel8))
                                        .addGap(14, 14, 14)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jfecha, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(degustacion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(renta)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(boca))
                            .addComponent(jcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jhora, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel9)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jminutos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(tevent, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addComponent(Bagendar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(205, 205, 205)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bAceptar)
                    .addComponent(jButton4)
                    .addComponent(Bbuscar))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jfecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jcliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(degustacion)
                        .addComponent(renta)
                        .addComponent(boca)
                        .addComponent(jeve, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jminutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(jhora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9)
                        .addComponent(jLabel10)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tevent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Bagendar)
                .addGap(16, 16, 16)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel1.getAccessibleContext().setAccessibleName("Eventos Proximos:");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jhoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jhoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jhoraActionPerformed

    private void BagendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BagendarActionPerformed
    String eventos;
        Evento evento = new Evento();
    evento.setIdevento(0);
    int x=jcliente.getSelectedIndex();
    evento.setIdcliente(cl[x]);
    evento.setLugar(tevent.getText());
    int ano= jDateChooser2.getCalendar().get(Calendar.YEAR);
    int dia= jDateChooser2.getCalendar().get(Calendar.DAY_OF_MONTH);
    int mes= jDateChooser2.getCalendar().get(Calendar.MONTH);
    mes=mes+1;
    String fechas=ano+"/"+mes+"/"+dia;
    evento.setFecha(fechas);
    evento.setHora(jhora.getSelectedItem()+":"+jminutos.getSelectedItem());
    if(jeve.getSelectedItem()!=""){
      eventos=(String) jeve.getSelectedItem();
     evento.setEvento(eventos);
    }else{
    if(degustacion.isSelected()){
        eventos="Degustacion";
        evento.setEvento(eventos);
    }if(renta.isSelected()){
        eventos="Renta equipo";
        evento.setEvento(eventos);
    }if(boca.isSelected()){
        eventos="Bocadillos";
        evento.setEvento(eventos);
    }
    
    
    }
    
        evento.almacenar();
        mostrardatos();
        
    
    
    
    }//GEN-LAST:event_BagendarActionPerformed
    
    private void jclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jclienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jclienteActionPerformed

    private void BbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BbuscarActionPerformed

String res;
int band=0;

conectar con=new conectar();
Connection reg=con.conexion();

 String formato = jDateChooser2.getDateFormatString();
Date date = jDateChooser2.getDate();
SimpleDateFormat sdf = new SimpleDateFormat(formato);
String fnacim = String.valueOf(sdf.format(date));
fecha=fnacim;
try {
 String sql="SELECT * FROM agenda";// WHERE fecha='"+fecha+"'";
 Statement st = reg.createStatement();
 ResultSet rs = st.executeQuery(sql);
 while(rs.next()){
    if (date.equals(rs.getDate(6))){
    band=band+1;}
            }
if (band==0){
 JOptionPane.showMessageDialog(null,fnacim, "¡FECHA DISPONIBLE!", JOptionPane.YES_OPTION);
}else{JOptionPane.showMessageDialog(null, "Usted tiene: "+band+" eventos agendados para esta fecha "+fnacim, "¡Advertencia!", JOptionPane.ERROR_MESSAGE);} 
 
 }
catch (Exception e) {
JOptionPane.showMessageDialog(null, "Elija Una Fecha", "Error!", JOptionPane.ERROR_MESSAGE);
//jDateChooser2.setDate(null);
}
//buscar
//buscar
    }//GEN-LAST:event_BbuscarActionPerformed

    private void bAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAceptarActionPerformed

        // TODO add your handling code here:
  String formato = jDateChooser2.getDateFormatString();
Date date = jDateChooser2.getDate();
SimpleDateFormat sdf = new SimpleDateFormat(formato);
String fnacim = String.valueOf(sdf.format(date));
fecha=fnacim;
        jfecha.setText(fecha);
    }//GEN-LAST:event_bAceptarActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
this.dispose(); //pantalla2.setVisible(false);      
 // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jeveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jeveActionPerformed
      if(jeve.getSelectedItem()!=""){
      renta.setEnabled(false);
    
      degustacion.setEnabled(false);
      boca.setEnabled(false);}
    }//GEN-LAST:event_jeveActionPerformed

    private void rentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rentaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pantalla2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pantalla2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pantalla2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pantalla2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new pantalla2().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(pantalla2.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bagendar;
    private javax.swing.JButton Bbuscar;
    private javax.swing.ButtonGroup TIPOEV;
    private javax.swing.JButton bAceptar;
    private javax.swing.JRadioButton boca;
    private javax.swing.JRadioButton degustacion;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox jComboBox4;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox jcliente;
    private javax.swing.JComboBox jeve;
    private javax.swing.JTextField jfecha;
    private javax.swing.JComboBox jhora;
    private javax.swing.JComboBox jminutos;
    private java.awt.Label label1;
    private javax.swing.JRadioButton renta;
    private javax.swing.JTable tabeven;
    private javax.swing.JTextField tevent;
    // End of variables declaration//GEN-END:variables

private void cbbclient() throws SQLException{
try{
conectar con =new conectar();
Connection cn=con.conexion();
Statement st=cn.createStatement();
ResultSet rs;
  System.out.println("pasa 1");
rs = st.executeQuery("select * from cliente");
 System.out.println("entra a cliente");
jcliente.removeAllItems();
 System.out.println("borra combo");
 int i=0;
 int j=0;
while(rs.next()){
jcliente.addItem(rs.getString(2)+" "+rs.getString(3)+" "+rs.getString(4));
i=rs.getInt(1);
cl[j]=i;
j++;

}
}catch (Exception e) {
JOptionPane.showMessageDialog(null, "No se encontraron clientes", "Error!", JOptionPane.ERROR_MESSAGE);
}

}

private void mostrardatos(){
 conectar con =new conectar();
Connection cn=con.conexion();
conectar cons =new conectar();
Connection cns=cons.conexion();
    DefaultTableModel modelo= new DefaultTableModel();
    modelo.addColumn("fecha");
    modelo.addColumn("hora");
    modelo.addColumn("cliente");
    modelo.addColumn("tipo evento");
    modelo.addColumn("Lugar");
    tabeven.setModel(modelo);
   String sql="SELECT * FROM agenda";
   String sqls="Select *from cliente";
   int band2=0;
    try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            Statement sts = cns.createStatement();
           
                    while(rs.next()){
             
  
                Object []ob=new Object[6];
                ob[0]=rs.getDate(6);//fecha
                ob[1]=rs.getTime(3);//hora
                ob[2]=rs.getString(2);//cliente
                ob[3]=rs.getString(4);//evento
                ob[4]=rs.getString(5);//lugar
                /////////////////////////////////////////////////////////////////
                      try {
                        ResultSet rst = sts.executeQuery(sqls);
                            while(rst.next()){
                                if (rs.getString(2).equals(rst.getString(1))){
                                 ob[2]=rst.getString(2)+" "+rst.getString(3)+" "+rst.getString(4);//cliente
                                     System.out.println("entra");
                                 }
                             System.out.println(rst.getString(2)+" "+rst.getString(3)+" "+rst.getString(4));
                            System.out.println(rs.getString(2));
                            System.out.println(rst.getString(1));
                                }
            
                             }
                    catch (Exception e) {
                                JOptionPane.showMessageDialog(null, "", "Error!", JOptionPane.ERROR_MESSAGE);

}
                
                
                
                
                
                /////////////////////////////////////////////////////////////////
                modelo.addRow(ob);
            }
            tabeven.setModel(modelo);
        } catch (SQLException ex) {
            Logger.getLogger(pantalla2.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}


