-- MySQL Script generated by MySQL Workbench
-- 12/21/14 15:31:42
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bd_banquetesMexico
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bd_banquetesMexico
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd_banquetesMexico` DEFAULT CHARACTER SET latin1 ;
USE `bd_banquetesMexico` ;

-- -----------------------------------------------------
-- Table `bd_banquetesMexico`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_banquetesMexico`.`cliente` (
  `idCliente` INT(11) NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `ApPaterno` VARCHAR(45) NOT NULL,
  `ApMaterno` VARCHAR(45) NOT NULL,
  `Sexo` CHAR(1) NULL DEFAULT NULL,
  `Calle` VARCHAR(45) NULL DEFAULT NULL,
  `Numero` VARCHAR(45) NULL DEFAULT NULL,
  `Colonia` VARCHAR(45) NULL DEFAULT NULL,
  `Ciudad` VARCHAR(45) NULL DEFAULT NULL,
  `Codigo_Postal` VARCHAR(45) NULL DEFAULT NULL,
  `Correo_Electronico` VARCHAR(45) NULL DEFAULT NULL,
  `RFC` VARCHAR(45) NULL DEFAULT NULL,
  `dirFB` VARCHAR(45) NULL DEFAULT NULL,
  `dirTW` VARCHAR(45) NULL DEFAULT NULL,
  `telCel` VARCHAR(45) NULL DEFAULT NULL,
  `telCasa` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `bd_banquetesMexico`.`agenda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_banquetesMexico`.`agenda` (
  `idevento` INT(11) NOT NULL AUTO_INCREMENT,
  `fkidcliente` INT(11) NOT NULL,
  `hora_evento` TIME NOT NULL,
  `tipoevento` VARCHAR(45) NOT NULL,
  `ciudadevento` VARCHAR(45) NOT NULL,
  `fechaevento` DATE NOT NULL,
  PRIMARY KEY (`idevento`),
  INDEX `fkidcliente` (`fkidcliente` ASC),
  CONSTRAINT `fkidcliente`
    FOREIGN KEY (`fkidcliente`)
    REFERENCES `bd_banquetesMexico`.`cliente` (`idCliente`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `bd_banquetesMexico`.`cotizar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_banquetesMexico`.`cotizar` (
  `idcotizacion` INT(11) NOT NULL AUTO_INCREMENT,
  `numpax` INT(11) NOT NULL,
  `totalpax` FLOAT NOT NULL,
  `costototal` FLOAT NOT NULL,
  `estado` INT(11) NOT NULL,
  `observaciones` TEXT NULL DEFAULT NULL,
  `fechacotizar` DATETIME NOT NULL,
  `fkidagenda` INT(11) NOT NULL,
  PRIMARY KEY (`idcotizacion`),
  INDEX `fkidagenda` (`fkidagenda` ASC),
  CONSTRAINT `fkidagenda`
    FOREIGN KEY (`fkidagenda`)
    REFERENCES `bd_banquetesMexico`.`agenda` (`idevento`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `bd_banquetesMexico`.`insumos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_banquetesMexico`.`insumos` (
  `idinsumo` INT(11) NOT NULL AUTO_INCREMENT,
  `nombreinsumo` VARCHAR(80) NOT NULL,
  `descripcion` TEXT NULL DEFAULT NULL,
  `forma` VARCHAR(60) NULL DEFAULT NULL,
  `tamaño` VARCHAR(60) NULL DEFAULT NULL,
  `color` VARCHAR(60) NULL DEFAULT NULL,
  `diseño` VARCHAR(60) NULL DEFAULT NULL,
  `cintilla` TINYINT(1) NULL DEFAULT NULL,
  `precio` FLOAT NULL DEFAULT NULL,
  `tipocatalogo` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idinsumo`),
  INDEX `fkidcatalogo_idx` (`tipocatalogo` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `bd_banquetesMexico`.`cotinsumo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_banquetesMexico`.`cotinsumo` (
  `idcotizacion` INT(11) NOT NULL,
  `idinsumo` INT(11) NOT NULL,
  `numeroinsumos` INT(11) NOT NULL,
  INDEX `fkinsumo` (`idinsumo` ASC),
  INDEX `fkcotizacion` (`idcotizacion` ASC),
  CONSTRAINT `fkcotizacion`
    FOREIGN KEY (`idcotizacion`)
    REFERENCES `bd_banquetesMexico`.`cotizar` (`idcotizacion`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fkinsumo`
    FOREIGN KEY (`idinsumo`)
    REFERENCES `bd_banquetesMexico`.`insumos` (`idinsumo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `bd_banquetesMexico`.`estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_banquetesMexico`.`estado` (
  `idEstado` INT(11) NOT NULL AUTO_INCREMENT,
  `nombreestado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEstado`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `bd_banquetesMexico`.`venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_banquetesMexico`.`venta` (
  `idventa` INT(11) NOT NULL AUTO_INCREMENT,
  `fechaVenta` DATETIME NOT NULL,
  `Cotizacion_idCotizacion` INT(11) NOT NULL,
  `costosalon` FLOAT NULL DEFAULT NULL,
  `costomusica` FLOAT NULL DEFAULT NULL,
  `costootros` FLOAT NULL DEFAULT NULL,
  `costototal` FLOAT NOT NULL,
  PRIMARY KEY (`idventa`),
  INDEX `fkidcotizar` (`Cotizacion_idCotizacion` ASC),
  CONSTRAINT `fkidcotizar`
    FOREIGN KEY (`Cotizacion_idCotizacion`)
    REFERENCES `bd_banquetesMexico`.`cotizar` (`idcotizacion`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `bd_banquetesMexico`.`pagos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_banquetesMexico`.`pagos` (
  `idPago` INT(11) NOT NULL AUTO_INCREMENT,
  `Venta_idVenta` INT(11) NOT NULL,
  `fechaPago` DATETIME NULL DEFAULT NULL,
  `montoPago` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`idPago`),
  INDEX `fkidventa` (`Venta_idVenta` ASC),
  CONSTRAINT `fkidventa`
    FOREIGN KEY (`Venta_idVenta`)
    REFERENCES `bd_banquetesMexico`.`venta` (`idventa`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `bd_banquetesMexico`.`tareas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_banquetesMexico`.`tareas` (
  `idTareas` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre_tarea` VARCHAR(45) NOT NULL,
  `estado_tarea` INT(11) NOT NULL,
  `fkidagenda` INT(11) NOT NULL,
  PRIMARY KEY (`idTareas`),
  INDEX `estadotarea` (`estado_tarea` ASC),
  INDEX `evento` USING BTREE (`fkidagenda` ASC),
  CONSTRAINT `estadotarea`
    FOREIGN KEY (`estado_tarea`)
    REFERENCES `bd_banquetesMexico`.`estado` (`idEstado`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `evento`
    FOREIGN KEY (`fkidagenda`)
    REFERENCES `bd_banquetesMexico`.`agenda` (`idevento`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = latin1;

USE `bd_banquetesMexico` ;

-- -----------------------------------------------------
-- Placeholder table for view `bd_banquetesMexico`.`cotizacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_banquetesMexico`.`cotizacion` (`idcotizacion` INT, `idevento` INT, `Nombre` INT, `ApPaterno` INT, `ApMaterno` INT, `observaciones` INT, `estado` INT, `costototal` INT, `nombreinsumo` INT, `descripcion` INT, `fechacotizar` INT, `ciudadevento` INT, `fechaevento` INT, `tipoevento` INT);

-- -----------------------------------------------------
-- View `bd_banquetesMexico`.`cotizacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_banquetesMexico`.`cotizacion`;
USE `bd_banquetesMexico`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `cotizacion` AS select `cotizar`.`idcotizacion` AS `idcotizacion`,`agenda`.`idevento` AS `idevento`,`cliente`.`Nombre` AS `Nombre`,`cliente`.`ApPaterno` AS `ApPaterno`,`cliente`.`ApMaterno` AS `ApMaterno`,`cotizar`.`observaciones` AS `observaciones`,`cotizar`.`estado` AS `estado`,`cotizar`.`costototal` AS `costototal`,`insumos`.`nombreinsumo` AS `nombreinsumo`,`insumos`.`descripcion` AS `descripcion`,`cotizar`.`fechacotizar` AS `fechacotizar`,`agenda`.`ciudadevento` AS `ciudadevento`,`agenda`.`fechaevento` AS `fechaevento`,`agenda`.`tipoevento` AS `tipoevento` from ((((`agenda` join `cotizar` on((`cotizar`.`fkidagenda` = `agenda`.`idevento`))) join `cliente` on((`agenda`.`fkidcliente` = `cliente`.`idCliente`))) join `cotinsumo` on((`cotinsumo`.`idcotizacion` = `cotizar`.`idcotizacion`))) join `insumos` on((`cotinsumo`.`idinsumo` = `insumos`.`idinsumo`))) where (`insumos`.`tipocatalogo` = 'salon');

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
